## Concatenation (Stacking the Data)
- `concat()` is like putting dataframes together without merging rows.

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    'Name':['Aryan','Raj'],
    'Age':[20,21]
})

df2 = pd.DataFrame({
    'Name':['Priya','Neha'],
    'Age':[22,23]
})

In [2]:
pd.concat([df1,df2])

    Name  Age
0  Aryan   20
1    Raj   21
0  Priya   22
1   Neha   23

### Reset Index

In [3]:
pd.concat([df1,df2], ignore_index=True)

    Name  Age
0  Aryan   20
1    Raj   21
2  Priya   22
3   Neha   23

In [4]:
# Horizontal concatenation
pd.concat([df1,df2],axis=1)

    Name  Age   Name  Age
0  Aryan   20  Priya   22
1    Raj   21   Neha   23

In [6]:
# Join
# works using index
df1 = pd.DataFrame({
    'Name' : ['Aryan','Raj']
} , index=[1,2])

df2 = pd.DataFrame({
    'Marks' : [90,95]
} , index=[1,2])

In [7]:
df1.join(df2)

    Name  Marks
1  Aryan     90
2    Raj     95

In [8]:
df1 = pd.DataFrame({
    'id' : [1,2,3],
    'name' : ['A','B','C']
})
marks = pd.DataFrame({
    'id' : [1,2,3],
    'marks' : [90,80,95]
})
pd.merge(df1,marks,on='id')

   id name  marks
0   1    A     90
1   2    B     80
2   3    C     95